AWSTemplateFormatVersion: '2010-09-09'
Description: 'YouTube Audio Extractor - Downloads videos and extracts audio as MP3'

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket containing the Lambda layer ZIP
    Default: 'cloudytdl-20250330150643'

  LayerKey:
    Type: String
    Description: S3 key for the Lambda layer ZIP file
    Default: ffmpeg-ytdlp-lambda-layer.zip

  OutputBucketName:
    Type: String
    Description: S3 bucket where extracted MP3 files will be stored
    Default: 'cloudytdl-20250330150643'

Resources:
  # S3 bucket for audio output
  OutputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketName
      VersioningConfiguration:
        Status: Enabled

  # FFmpeg and yt-dlp Lambda layer
  FFmpegYtDlpLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: ffmpeg-ytdlp-layer
      Description: Lambda Layer containing FFmpeg and yt-dlp executables
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref LayerKey
      CompatibleRuntimes:
        - python3.11
      CompatibleArchitectures:
        - x86_64

  # Lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetBucketLocation
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}'
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: S3OutputAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${OutputBucketName}/*'
                
  # Lambda function for extracting audio
  AudioExtractorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: youtube-audio-extractor
      Description: Downloads YouTube videos and extracts MP3 audio
      Runtime: python3.11
      Handler: extrct.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 2048
      Timeout: 300
      Layers:
        - !Ref FFmpegYtDlpLayer
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucketName
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: lambda.zip

Outputs:
  AudioExtractorFunctionArn:
    Description: ARN of the YouTube audio extractor Lambda function
    Value: !GetAtt AudioExtractorFunction.Arn
    
  OutputBucketName:
    Description: Name of the bucket where extracted audio files are stored
    Value: !Ref OutputBucket
