AWSTemplateFormatVersion: '2010-09-09'
Description: 'YouTube Audio Extractor - Downloads videos and extracts audio as MP3'

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket containing the Lambda layer ZIP
    Default: 'cloudytdl-20250330150643'

  OutputBucketName:
    Type: String
    Description: S3 bucket where extracted MP3 files will be stored
    Default: 'cloudytdl-20250330150643'


  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID in which to deploy the Lambda function
    Default: vpc-0d1b3423fbadeda4b

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The Subnet ID in which to deploy the Lambda function
    Default: subnet-04ac751ef7d57da9a

Resources:
  # S3 bucket for audio output
  # OutputBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Ref OutputBucketName
  #     VersioningConfiguration:
  #       Status: Enabled


  # Lambda execution role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
                - s3:GetBucketLocation
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}'
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
              Resource: !Sub 'arn:aws:s3:::${S3BucketName}/*'
        - PolicyName: S3OutputAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${OutputBucketName}/*'
                
  # Lambda function for extracting audio
  AudioExtractorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: youtube-audio-extractor
      Description: Downloads YouTube videos and extracts MP3 audio
      Role: !GetAtt LambdaExecutionRole.Arn
      MemorySize: 2048
      Timeout: 300
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucketName
      PackageType: Image
      Code:
        ImageUri: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/yt-dlp-extract:latest"

Outputs:
  AudioExtractorFunctionArn:
    Description: ARN of the YouTube audio extractor Lambda function
    Value: !GetAtt AudioExtractorFunction.Arn
    
  OutputBucketName:
    Description: Name of the bucket where extracted audio files are stored
    Value: !Ref OutputBucketName
